language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - composer selfupdate
  - composer install
  - phpunit --configuration phpunit.xml

branches:
  except:
    - gh-pages

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

