language: php

dist: trusty

matrix:
  fast_finish: true
  include:
    # Requires older Precise image
    - php: 5.3
      sudo: true
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

script:
  - composer selfupdate
  - composer install
  - ./vendor/bin/phpunit --configuration phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 src tests/suites

branches:
  except:
    - gh-pages

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

sudo: false