language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: hhvm

script:
  - composer selfupdate
  - composer install
  - ./vendor/bin/phpunit --configuration phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 src tests/suites

branches:
  except:
    - gh-pages

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

sudo: false